### ISSUE TITLE
Encountering "Techstack is invalid" when the Technology scan has no language level

### ISSUE THREAD

**Issue by cripher** [fod-dev/fod-uploader-java#10]
Hello,

Please see issue found.
Issue: Encountering "Techstack is invalid" when the Technology scan has no language level

Steps to reproduce:
1. Generate a BSI where the Techstack has no language level (I used Objective C/C++)
2. Start a scan using Fodupload.jar.

Expected result: Scan will be created.
Actual result: Techstack is invalid

See screenshot below for your reference.

![techstack is invalid](https://cloud.githubusercontent.com/assets/23040498/24743931/bc002ef2-1ae2-11e7-92ce-73add7df0687.png)

**Comment by petebeegle** [comment]
This issue only affects iOS Swift & Objective-C/C++

**Comment by tcappetto** [comment]
@cripher Please provide a screenshot of the place you generated this bsi url, I don't see how you could have generated this bsiURL without typing the TechStack in yourself.

**Comment by gilseara** [comment]
@tcappetto, you can reproduce on any mobile application on the FoD portal trying to start a static scan selecting "iOS" for static scan. The generated BSI URL is similar to the one shown on the snapshot by @cripher

**Comment by tcappetto** [comment]
Jose and/or Able, please confirm this issue is resolved.  Thanks.

**Comment by mtgibbs** [comment]
[3.0.2](https://github.com/fod-dev/fod-uploader-java/releases/tag/v3.0.2)
