### ISSUE TITLE
RE-OPENED: Encountering "Techstack is invalid" when the Technology scan has no language level

### ISSUE THREAD

**Issue by cripher** [fod-dev/fod-uploader-java#13]
Related to Issue: https://github.com/fod-dev/fod-uploader-java/issues/10

Hello,

Good day.
Issue still affecting the foduploader.
Issue: Encountering "Techstack is invalid" when the Technology scan has no language level
Foduploader version: v3.0.1

Steps to reproduce:

1. Generate a BSI where the Techstack has no language level (I used Objective C/C++)
2. Start a scan using Fodupload.jar.

Expected result: Scan will be created.
Actual result: Techstack is invalid

See screenshot below for your reference.
![technology stack is invalid](https://user-images.githubusercontent.com/23040498/30816548-d23394f0-a248-11e7-8311-2d06fb2c8e59.png)

**Comment by mtgibbs** [comment]
This has nothing to do with having no language level and has to do with improper handling of the plus sign and encoding when calling the FoD API, per the original bug #10.  Next time just reopen the same issue to easier tracking as well.  It keeps the discussion in one place.

**Comment by mtgibbs** [comment]
Fixed in [3.0.2](https://github.com/fod-dev/fod-uploader-java/releases/tag/v3.0.2).
