### ISSUE TITLE
TAMs have confirmed that the latest version of fodupload.jar has ThirdParty flag turned on by default

### ISSUE THREAD

**Issue by tcappetto** [fod-dev/fod-uploader-java#14]
In previous versions of fodupload.jar, scanning third party -excludeThirdPartyLibs or -x
was an option that was on by default. In this latest version it is off.  TAMs are concerned that will result in confusion with customers having to update their commands and is responsible for a huge increase in the number of larger payloads due to scanning third party libraries.  

Could we please make the default on again like it was before?  Thanks in advance.

**Comment by s4huey2012** [comment]
I believe the issue was introduce here:

Flag parameters no longer require setting a value (e.g. -x true). Now, simply adding the flag sets it to true. It is false otherwise. This change affects the following parameters:

-b
-r
-x
-s
-purchase

**Comment by mtgibbs** [comment]
We can simply invert the flag to be something like "includeThirdParty" and then it's presence would activate the feature and be excluding by default.  That sound reasonable?

**Comment by tcappetto** [comment]
Sounds great!


Tim Cappetto

Software Development Escalation Manager

Fortify On Demand

Telephone: +1 470-212-9592

Email: Timothy.K.Cappetto@microfocus.com<mailto:Timothy.K.Cappetto@microfocus.com>

5555 Windward Pkwy, Alpharetta, GA 30004



Upcoming OOO:

[cid:image001.png@01D33D19.0BA9A3E0]
MicroFocus.com<https://www.microfocus.com/>  |  @microfocus<https://twitter.com/MicroFocus>
