### ISSUE TITLE
Is it a good way for encoding BSI token url. 

### ISSUE THREAD

**Issue by gr5nextgen2017** [fod-dev/fod-uploader-java#24]
According to my experience can't automate release creation, process FoD upload process  from bash or shell scripts via new encryption approach

example from my case

-u 'https://api.ams.fortify.com/bsi2.aspx?tid=122&tc=xxxx&pv='${RIID}'&payloadType=ANALYSIS_PAYLOAD&astid=111&ts=JS%252FXML%252FHTML'

Can I pass RELEASE ID ='$RIID'  in new approach?

**Comment by mtgibbs** [comment]
No, you can't.

**Comment by mtgibbs** [comment]
@gr5nextgen2017 

But!  The URL parsing is backward compatible.  So you don't need to worry about that if you're using that approach.  If you don't care to share more specifics with me here, I think we can probably come up with a way for you to do what you want.
